#!/usr/bin/env bash
# Install mpv-getsub-lua as a Celluloid plugin.
#
# Celluloid auto-loads every file in ~/.config/celluloid/scripts/ via mpv's
# `load-script` (its native plugin mechanism), and reads script-opts from
# ~/.config/celluloid/script-opts/<script-name>.conf. We drop a thin wrapper
# there that adds the project to package.path and runs the real main.lua.
#
# Usage: ./scripts/install-celluloid.sh [--uninstall]
set -euo pipefail
cd "$(dirname "$0")/.."

SCRIPT_DIR="$(cd mpv-getsub-lua && pwd)"
MAIN_LUA="$SCRIPT_DIR/main.lua"
CELL_CFG="${XDG_CONFIG_HOME:-$HOME/.config}/celluloid"
SCRIPTS_DIR="$CELL_CFG/scripts"
OPTS_DIR="$CELL_CFG/script-opts"
WRAPPER="$SCRIPTS_DIR/mpv-getsub-lua.lua"
UNINSTALL=0

for arg in "$@"; do
    case "$arg" in
        --uninstall) UNINSTALL=1 ;;
        *) echo "unknown arg: $arg" >&2; exit 2 ;;
    esac
done

if [[ "$UNINSTALL" -eq 1 ]]; then
    rm -f "$WRAPPER"
    echo "Removed $WRAPPER (kept $OPTS_DIR/mpv-getsub-lua.conf if present)"
    exit 0
fi

[[ -f "$MAIN_LUA" ]] || { echo "main.lua not found at $MAIN_LUA" >&2; exit 1; }

mkdir -p "$SCRIPTS_DIR" "$OPTS_DIR"

cat > "$WRAPPER" <<EOF
-- Celluloid plugin wrapper for mpv-getsub-lua (generated by install-celluloid.sh)
-- Celluloid load-scripts every file in this directory; the real script lives
-- in the project checkout, so we extend package.path and run it.
package.path = "$SCRIPT_DIR/?.lua;" .. package.path
dofile("$MAIN_LUA")
EOF

echo "Installed for Celluloid."
echo "  wrapper : $WRAPPER"
echo "  script  : $MAIN_LUA"
echo
echo "Config: copy docs/CONFIG.example.conf to $OPTS_DIR/mpv-getsub-lua.conf"
echo "and fill in your API key. Restart Celluloid, open a video, press 'n'."
